name: Build LaTeX Editor Windows
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.2.4'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        dir: '${{ github.workspace }}/qt/'
        install-deps: 'true'
    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build
    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/qt/6.2.4/msvc2019_64
    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config Release
    - name: Deploy Qt
      working-directory: ${{github.workspace}}/build/Release
      run: |
        $ENV:PATH += ";${{ github.workspace }}/qt/6.2.4/msvc2019_64/bin"
        windeployqt.exe LaTeXEditor.exe
    - name: List Release Directory Contents
      working-directory: ${{github.workspace}}/build/Release
      shell: bash
      run: ls -la
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: LaTeXEditor-windows-latest
        path: ${{github.workspace}}/build/Release
