name: Build LaTeX Editor for Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.2.4'
        host: 'linux'
        target: 'desktop'
        arch: 'gcc_64'
        dir: '${{ github.workspace }}/qt/'
        install-deps: 'true'

    - name: Install additional dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev

    - name: List Qt installation directory
      run: |
        ls -R ${{ github.workspace }}/qt/

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: |
        export Qt6_DIR=${{ github.workspace }}/qt/6.2.4/gcc_64/lib/cmake/Qt6
        cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=${{ github.workspace }}/qt/6.2.4/gcc_64

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config Release

    - name: List build directory
      run: ls -R ${{github.workspace}}/build

    - name: Create deployment directory
      run: |
        mkdir -p ${{github.workspace}}/deploy/lib
        cp ${{github.workspace}}/build/LaTeXEditor ${{github.workspace}}/deploy/
        cp -L ${{ github.workspace }}/qt/6.2.4/gcc_64/lib/libQt6Core.so* ${{github.workspace}}/deploy/lib/
        cp -L ${{ github.workspace }}/qt/6.2.4/gcc_64/lib/libQt6Gui.so* ${{github.workspace}}/deploy/lib/
        cp -L ${{ github.workspace }}/qt/6.2.4/gcc_64/lib/libQt6Widgets.so* ${{github.workspace}}/deploy/lib/
        cp -r ${{ github.workspace }}/qt/6.2.4/gcc_64/plugins ${{github.workspace}}/deploy/

    - name: Create launch script
      run: |
        echo '#!/bin/bash' > ${{github.workspace}}/deploy/run_LaTeXEditor.sh
        echo 'DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"' >> ${{github.workspace}}/deploy/run_LaTeXEditor.sh
        echo 'export LD_LIBRARY_PATH="$DIR/lib:$LD_LIBRARY_PATH"' >> ${{github.workspace}}/deploy/run_LaTeXEditor.sh
        echo 'export QT_PLUGIN_PATH="$DIR/plugins"' >> ${{github.workspace}}/deploy/run_LaTeXEditor.sh
        echo '"$DIR/LaTeXEditor"' >> ${{github.workspace}}/deploy/run_LaTeXEditor.sh
        chmod +x ${{github.workspace}}/deploy/run_LaTeXEditor.sh

    - name: Create tarball
      run: tar -czvf LaTeXEditor-linux.tar.gz -C ${{github.workspace}}/deploy .

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: LaTeXEditor-linux-latest
        path: ${{github.workspace}}/LaTeXEditor-linux.tar.gz
