name: Build LaTeX Editor for Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.2.4'
          host: 'linux'
          target: 'desktop'
          arch: 'gcc_64'
          dir: '${{ github.workspace }}/qt/'
          install-deps: 'true'

      - name: Install additional dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/qt/6.2.4/gcc_64

      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cmake --build . --config Release

      - name: Create AppImage
        working-directory: ${{github.workspace}}/build
        run: |
          sudo apt-get install -y libfuse2
          wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
          chmod a+x linuxdeployqt-continuous-x86_64.AppImage
          ./linuxdeployqt-continuous-x86_64.AppImage LaTeXEditor -appimage

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: LaTeXEditor-linux-latest
          path: ${{github.workspace}}/build/LaTeXEditor*.AppImage