name: Build LaTeX Editor for macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13  # Use a recent macOS runner

    steps:
    - uses: actions/checkout@v4

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.2.4'
        host: 'mac'
        target: 'desktop'
        arch: 'clang_64'
        dir: '${{ github.workspace }}/qt/'
        install-deps: 'true'

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: |
        export Qt6_DIR=${{ github.workspace }}/qt/6.2.4/macos/lib/cmake/Qt6
        cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config Release -- -j1

    - name: Ad-hoc Signing
      working-directory: ${{github.workspace}}/build
      run: |
        codesign --force --deep --sign - LaTeXEditor.app

    - name: Create DMG
      working-directory: ${{github.workspace}}/build
      run: |
        hdiutil create -volname "LaTeXEditor" -srcfolder LaTeXEditor.app -ov -format UDZO LaTeXEditor.dmg

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: LaTeXEditor-macOS
        path: ${{github.workspace}}/build/LaTeXEditor.dmg
