name: Build LaTeX Editor for macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.2.4'
        host: 'mac'
        target: 'desktop'
        arch: 'clang_64'
        dir: '${{ github.workspace }}/qt/'
        install-deps: 'true'

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/qt/6.2.4/macos

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config Release

    - name: Deploy Qt
      working-directory: ${{github.workspace}}/build
      run: |
        ${{ github.workspace }}/qt/6.2.4/macos/bin/macdeployqt LaTeXEditor.app -dmg

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: LaTeXEditor-macos-latest
        path: ${{github.workspace}}/build/LaTeXEditor.dmg
